---
fixtures:
  forge_modules:
    apt: "puppetlabs/apt"
    augeas_core: "puppetlabs/augeas_core"
    concat: "puppetlabs/concat"
    epel: "puppet/epel"
    mysql: "puppetlabs/mysql"
    stdlib: "puppetlabs/stdlib"
    postgresql: "puppetlabs/postgresql"
    systemd: "puppet/systemd"
    yumrepo_core: "puppetlabs/yumrepo_core"
